config/routes.rb
LearnedToday::Application.routes.draw do
	match "/", to: "home#index", via: "get"
	match "/home", to: "home#index", via: "get"
	match "/fact/:fact_url", to: "home#show", via: "get"
	match "/fact/:fact_url/prev", to: "home#prev", via: "get"
	match "/fact/:fact_url/next", to: "home#next", via: "get"
end

app/models/fact.rb
class Fact
	attr_accessor :fact, :date, :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  def index
	@facts = Kaminari.paginate_array(process_xml_facts)
					 .page(params[:page])
					 .per(5)
  end

  def show
	facts = process_xml_facts
	@fact = facts.detect { |f| f.file == params[:fact_url].gsub('-','_') }
  end

  def prev
	facts = process_xml_facts
	required_index = get_index(facts) - 1
	@fact = facts[required_index]
	redirect_to "/fact/#{@fact.file.gsub('_','-')}"
  end

  def next
	facts = process_xml_facts
	required_index = get_index(facts) + 1
	required_index = required_index == facts.length ? 0 : required_index
	@fact = facts[required_index]
	redirect_to "/fact/#{@fact.file.gsub('_','-')}"	
  end

  private

	def get_index(facts)
		current_fact = facts.detect { |f| f.file == params[:fact_url].gsub('-','_') }
		current_index = facts.find_index(current_fact)		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
require 'nokogiri'

module HomeHelper
	def process_xml_facts
		@files = procdir(Rails.root.join 'facts/xml')
		@facts = Array.new
		@files.each do |file|
			@fact = translate_xml(file)
			@facts.push(@fact)
		end
		@facts = @facts.sort_by! {
			|fact| Date.strptime(fact.date, "%m/%d/%Y")
		}
		@facts.reverse!
	end
	
	def process_txt_facts
		@files = procdir(Rails.root.join 'facts/txt')
		@facts = Array.new
		@files.each do |file|
			@fact = create_fact(file)
			@facts.push(@fact)
		end
		@facts		
	end
	
	def process_facts
		@files = procdir(Rails.root.join 'facts/yml')
		@facts = Array.new
		@files.each do |file|
			@fact = translate_yaml(YAML::load_file(file))
			@facts.push(@fact)
		end
		@facts
	end

	def create_fact(file)
		n_fact = Fact.new
		n_fact.fact = read_file(file)
		n_fact.date = read_file_date(file)
		n_fact
	end

	def translate_yaml(yml)
		n_fact = Fact.new
		n_fact.fact = yml["fact"]
		n_fact.date = yml["date"]
		n_fact
	end

	def translate_xml(xml)
		n_fact = Fact.new
		xml_parsed = Nokogiri::XML(File.open(xml).read)
		n_fact.fact = get(xml_parsed, "content")
		n_fact.date = get(xml_parsed, "date")
		n_fact.file = File.basename(xml, ".*")
		n_fact
	end

	private
		def procdir(dir)
		  files = Dir[ File.join(dir, '**', '*') ].reject { |p| File.directory? p }
		  files.reverse
		end

		def read_file(file)
			f = File.open(file)
			f.read
		end

		def read_file_date(file)
			mtime = File.ctime(file)
			date_str = "#{mtime.month}/#{mtime.day}/#{mtime.year}"
		end

		def get(xml_parsed, node_name)
			node = xml_parsed.xpath("//#{node_name}").first
			node.content.gsub(/\n\s+/, "")
		end
end

app/views/home/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = '<%= LearnedToday::Application.config.disqus_short_name %>';
    var disqus_identifier = "<%= @fact.file.gsub('_','-') %>";
    var disqus_url = '<%= LearnedToday::Application.config.site_base_url %>/fact/<%= @fact.file.gsub('_','-') %>';
    var disqus_developer = <%= Rails.env.production? ? 0 : 1 %>;

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script');
        s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    } ());
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/home/_fork.html.erb
<div class="github-fork-ribbon-wrapper right-bottom">
	<div class="github-fork-ribbon">
		<a href="https://github.com/karthik25/learned-today" target="_blank">Fork me on GitHub</a>
	</div>
</div>

app/views/home/_pager.html.erb
<div>
	<div style="float: left"><a href="/fact/<%= @fact.file.gsub('_','-') %>/prev">&lt;&lt; previous</a></div>
	<div style="float: right"><a href="/fact/<%= @fact.file.gsub('_','-') %>/next">next &gt;&gt;</a></div>
</div>
<br style="clear: both" /><br/>

app/views/home/index.html.erb
<br /><br />

<% @facts.each do |fact| %>
	<div class="panel panel-default">
	  <div class="panel-heading">Learnt on <strong><%= fact.date %></strong></div>
	  <div class="panel-body">
		<%= fact.fact.html_safe %>
		<br/><br/>
		<i class="glyphicon glyphicon-comment" style="vertical-align:middle"></i> <a href="/fact/<%= fact.file.gsub('_','-') %>">Comments</a>
	  </div>
	</div>
<% end %>

<%= paginate @facts %>

<%= render "fork" %>

app/views/home/show.html.erb
<br /><br />

<%= render "pager" %>

<div class="panel panel-default">
  <div class="panel-heading">Learnt on <strong><%= @fact.date %></strong></div>
  <div class="panel-body">
	<%= @fact.fact.html_safe %>
  </div>
</div>

<%= render "disqus" %>

<%= render "fork" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails :: Learned Today</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">rails :: learned today</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
			  <%= link_to "Home", home_path %>
            </li>            
            <li>
              <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal">About</a>
            </li>
          </ul>
        </div>
      </div>
    </div>

	<br/><br/><br/>
	<div class="container">
		<%= yield %>
		<br/><br/>
		<%= render "shared/footer" %>
	</div>

	<%= render "shared/about" %>
</body>
</html>

app/views/shared/_about.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="myModalLabel">About</h4>
		  </div>
		  <div class="modal-body">
			First of all, thanks for visiting this site! My first intention in creating this site is to develop a fully fledged, but minimal rails
			application since I am a beginner. Second, I wanted a journal where I could keep track of stuff I learnt (& learn) about rails! The source code is available on <a href="https://github.com/karthik25/learned-today" target="_blank">github</a>, feel free to fork it :)
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
		  </div>
		</div>
	</div>
</div>

app/views/shared/_footer.html.erb
<footer>
	<div class="row">
	  <div class="col-lg-12">		
		<p>Made by <a href="http://thekfactor.info" rel="nofollow">Karthik Ananthapadmanaban</a>. Contact him at <a href="mailto:thekfator@thekfactor.info">thekfactor (at) thekfactor.info</a>.</p>
		<p>Based on <a href="http://getbootstrap.com" rel="nofollow">Bootstrap</a>. Theme based on <a href="http://bootswatch.com/journal/" rel="nofollow">Bootswatch :: Journal</a>. Uses GitHub <a href="http://simonwhitaker.github.io/github-fork-ribbon-css/">Css</a> Ribbon. Comments powered by <a href="http://www.disqus.com" target="_blank">Disqus</a>.</p>
	  </div>
	</div>		
</footer>